### ISSUE TITLE
Some mistakes for Twixl Publisher

### ISSUE THREAD

**Issue by pieterclaerhout** [anselmh/Publishing-please#22]
Twixl Publisher version 3.3:
- supports iOS, Android and Amazon Kindle Fire
- Supports access control for groups if you use the entitlements option in the Twixl Distribution Platform
- Supports re-usable HTML5 snippets (we call them widgets)
- Hotspots on hotspots is supported (if you are meaning nested interacitvity with it)

**Comment by anselmh** [comment]
Thanks for reporting, will fix this soon!
