### ISSUE TITLE
Origami Engine

### ISSUE THREAD

**Issue by kariknapp** [anselmh/Publishing-please#24]
Would you consider adding Origami Engine to you fine list of digital publishing tools? Check it out here: origamiengine.com and download Katachi Magazine, Unlimited Magazine or Stipla Magazine as great examples of publishers on our platform. Thank you. If you have any questions or want to try it out (it's fun) - contact Karianne on kh@katachi.co 

Have a nice day!

Links: 
Origami Engine - http://origamiengine.com
Katachi Magazine - http://ktch.co/bw
The Unlimited - https://itunes.apple.com/us/app/the-unlimited-magazine-v2/id719689958?ls=1&mt=8
Stipla - https://itunes.apple.com/gb/app/stipla/id743873016?mt=8

**Comment by anselmh** [comment]
Hi @kariknapp, I think we can add it to the list. As I have no time (sorry also about the big delay here) I’d love if you could provide a Pull Request with the information needed. Happy to merge it.
